name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  #push:
  #  branches: ["**"]
  #  paths:
  #    - ".github/workflows/test.yaml"
  #    - "dist/**"
  #    - "src/**"
  #    - "package*.json"
  #    - "requirements*.txt"
  #    - "action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "INOP"
        run: |
          echo "This test must be updated for this action"
          exit 1

      - name: "Test Local Action"
        id: test
        uses: ./
        #with:
        #  tag: "test"

      - name: "Verify Outputs"
        if: ${{ !github.event.act }}
        run: |
          echo "url: '${{ steps.test.outputs.url }}'"
          if [ -z '${{ steps.test.outputs.url }}' ];then
            echo "No Output: url"
            exit 1
          fi

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
